CREATE TABLE IF NOT EXISTS `USERS`(
    USER_ID      	INT(11)     	NOT NULL 	AUTO_INCREMENT,
    USERNAME        VARCHAR(64)     NOT NULL,
    PASSWORD        VARCHAR(1024)   NOT NULL,
    PRIMARY KEY(USER_ID),
    UNIQUE(USERNAME)
) ENGINE=InnoDB;